//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billboard100Song
    {
        public int Year { get; set; }
        public int Position { get; set; }
        public string Song { get; set; }
        public string Artist { get; set; }
    }
}
